name: Análisis Estático con Detekt
run-name: Análisis de código por ${{ github.actor }}

on:
  push:
    branches:
      - 'main'
      - 'develop-g3'
      - 'features-**'
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    types: [opened]
    branches:
      - 'main'
      - 'develop-g3'
      - 'features-**'
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  detekt:
    name: Ejecutar Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Descargar Detekt
        run: |
          curl -sSLo detekt-cli.jar https://github.com/detekt/detekt/releases/download/v1.23.6/detekt-cli-1.23.6-all.jar
          mkdir -p build/detekt
          mv detekt-cli.jar build/detekt/detekt.jar

      - name: Descargar configuración por defecto de Detekt
        run: |
          curl -sSLo default-detekt-config.yml https://raw.githubusercontent.com/detekt/detekt/main/detekt-core/src/main/resources/default-detekt-config.yml

      - name: Parchear configuración inválida
        run: |
          sed -i 's/excludes: \[\]/excludes: ""/' default-detekt-config.yml

      - name: Ejecutar Detekt
        run: |
          mkdir -p .github/reports/detekt
          java -jar build/detekt/detekt.jar \
            --input src/main/kotlin/app \
            --report html:.github/reports/detekt/report.html \
            --config default-detekt-config.yml

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-detekt
          path: .github/reports/detekt/report.html

