name: Tests
run-name: Pruebas unitarias para @${{ github.actor }}
on:
  push:
    branches:
      - 'features-**'
    paths:
      - 'src/**'
  pull_request:
    types: [opened]
    branches:
      - 'develop-g3'
      - main
    paths:
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preparar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
          cache-dependency-path: |
            src/*.gradle*
            src/**/gradle-wrapper.properties

      - name: Unit test
        run: src/main/kotlin/gradlew testDebugUnitTest

      - name: Test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}